spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
    discovery:
      enabled: true

  application:
    name: Service-Gateway
  main:
    web-application-type: reactive
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#bezkoder:
#  app:
#    jwtCookieName: bezkoder
#    jwtSecret: bezKoderSecretKey
#   jwtExpirationMs: 82219516
